{ pkgs, ... }:
environment.systemPackages = with pkgs; [

     surface-control
     pkgs.gh
     pkgs.steam
     pkgs.pamtester
     pkgs.sstp
     pkgs.pam_u2f
     pkgs.sherlock
     pkgs.ipscan
     pkgs.bettercap
     pkgs.gnome.seahorse
     pkgs.duo-unix
     pkgs.ssh-mitm
     pkgs.john
     pkgs.johnny
     pkgs.firefox
     pkgs.bitwarden-desktop
     pkgs.bitwarden-cli
     pkgs.intel-media-driver
     pkgs.wgnord
     pkgs.htop
     pkgs.postman
     pkgs.git
     pkgs.appimage-run
     pkgs.wget
     pkgs.kitty
     pkgs.curl
     pkgs.wine64
     pkgs.vscode
     pkgs.coreutils-full
     pkgs.dnf5
     pkgs.dnf-plugins-core
     pkgs.dog
     pkgs.doggo
     pkgs.fwupd
     pkgs.fwupd-efi
     pkgs.intel-gpu-tools
     pkgs.vaapiIntel
     pkgs.intelmetool
     pkgs.inteltool
     pkgs.iperf2
     pkgs.iperf
     pkgs.iperf3d
     pkgs.kitty-img
     pkgs.kitty-themes
     pkgs.kittysay
     pkgs.libreoffice
     pkgs.mesa
     pkgs.mesa_drivers
     pkgs.metasploit
     pkgs.microsoft-edge
     pkgs.mono
     pkgs.mtr
     pkgs.mtr-exporter
     pkgs.mtr-gui
     pkgs.networkmanager-openvpn
     pkgs.networkmanager-sstp
     pkgs.networkmanager_strongswan
     pkgs.networkmanager-vpnc
     pkgs.nmap
     pkgs.onedrive
     pkgs.onedrivegui
     pkgs.pciutils
     pkgs.jdk22
     pkgs.openssl
     pkgs.openvpn
     pkgs.vpnc
     pkgs.winbox
     pkgs.wine64Packages.stableFull
     pkgs.wine64Packages.waylandFull
     pkgs.wineWow64Packages.waylandFull
     pkgs.wineWow64Packages.full
     pkgs.winetricks
     pkgs.wireguard-tools
     pkgs.wireshark
     pkgs.wg-netmanager
     pkgs.yubico-pam
     pkgs.yubico-piv-tool
     pkgs.yubikey-agent
     pkgs.yubikey-manager-qt
     pkgs.yubikey-personalization
     pkgs.remmina
     pkgs.firewalld
     
  ];
