{ pkgs, ... }:
{
environment.systemPackages = with pkgs; [
    pkgs.ad-miner
    pkgs.adenum
    pkgs.aesfix
    pkgs.aeskeyfind
    pkgs.aespipe
    pkgs.afflib
    pkgs.aflplusplus
    pkgs.afpfs-ng
    pkgs.aiodnsbrute
    pkgs.aircrack-ng
    pkgs.airgeddon
    pkgs.amass
    pkgs.amoco
    pkgs.androguard
    pkgs.android-udev-rules
    pkgs.apache-users
    pkgs.apachetomcatscanner
    pkgs.apkid
    pkgs.apkleaks
    pkgs.apktool
    pkgs.ares-rs
    pkgs.argus
    pkgs.argus-clients
    pkgs.arjun
    pkgs.arp-scan
    pkgs.arping
    pkgs.arpoison
    pkgs.asleap
    pkgs.asn
    pkgs.asnmap
    pkgs.assetfinder
    pkgs.atftp
    pkgs.bamf
    pkgs.batctl
    pkgs.bettercap
    pkgs.bind
    pkgs.binwalk
    pkgs.bkcrack
    pkgs.bloodhound
    pkgs.bloodhound-py
    pkgs.bmap-tools
    pkgs.boofuzz
    pkgs.braa
    pkgs.brakeman
    pkgs.bruteforce-luks
    pkgs.brutespray
    pkgs.bsdiff
    pkgs.bulk_extractor
    pkgs.bully
    pkgs.burpsuite
    pkgs.bvi
    pkgs.bytecode-viewer
    pkgs.cadaver
    pkgs.cantoolz
    pkgs.capstone
    pkgs.cargo-ndk
    pkgs.certgraph
    pkgs.certipy
    pkgs.certsync
    pkgs.cewl
    pkgs.cfr
    pkgs.chainsaw
    pkgs.chaos
    pkgs.checkpwn
    pkgs.checksec
    pkgs.chipsec
    pkgs.chisel
    pkgs.chkrootkit
    pkgs.chntpw
    pkgs.clair
    pkgs.clairvoyance
    pkgs.clamav
    pkgs.cloudlist
    pkgs.cmospwd
    pkgs.cntlm
    pkgs.coercer
    pkgs.commix
    pkgs.corkscrew
    pkgs.cowpatty
    pkgs.crackle
    pkgs.crackmapexec
    pkgs.crackql
    pkgs.creds
    pkgs.crlfuzz
    pkgs.crowbar
    pkgs.crunch
    pkgs.cryptsetup
    pkgs.ctypes_sh
    pkgs.dalfox
    pkgs.darkstat
    pkgs.davtest
    pkgs.dc3dd
    pkgs.dcfldd
    pkgs.ddosify
    pkgs.ddrescue
    pkgs.detect-secrets
    pkgs.dex2jar
    pkgs.dirb
    pkgs.dirstalk
    pkgs.dislocker
    pkgs.dive
    pkgs.dmg2img
    pkgs.dnschef
    pkgs.dnsenum
    pkgs.dnsmasq
    pkgs.dnsrecon
    pkgs.dnstracer
    pkgs.dnstwist
    pkgs.dnsx
    pkgs.dontgo403
    pkgs.doona
    pkgs.dorkscout
    pkgs.driftnet
    pkgs.dsniff
    pkgs.dublin-traceroute
    pkgs.dump1090
    pkgs.edb
    pkgs.elfkickers
    pkgs.elfutils
    pkgs.enum4linux
    pkgs.enum4linux-ng
    pkgs.eresi
    pkgs.etherape
    pkgs.ettercap
    pkgs.evil-winrm
    pkgs.evillimiter
    pkgs.exabgp
    pkgs.exiftool
    pkgs.exploitdb
    pkgs.ext4magic
    pkgs.extundelete
    pkgs.fcrackzip
    pkgs.feroxbuster
    pkgs.ffuf
    pkgs.fierce
    pkgs.findomain
    pkgs.firefox_decrypt
    pkgs.firewalk
    pkgs.flare-floss
    pkgs.flasm
    pkgs.foremost
    pkgs.fping
    pkgs.freeipmi
    pkgs.freeradius
    pkgs.freerdp
    pkgs.frida-tools
    pkgs.fscan
    pkgs.fwbuilder
    pkgs.gau
    pkgs.gdb
    pkgs.gdbgui
    pkgs.geoip
    pkgs.ghauri
    pkgs.ghdorker
    pkgs.ghidra
    pkgs.ghost
    pkgs.girsh
    pkgs.git-hound
    pkgs.gitleaks
    pkgs.gnuradio
    pkgs.gnutls
    pkgs.go-cve-search
    pkgs.gobuster
    pkgs.gomapenum
    pkgs.gospider
    pkgs.gowitness
    pkgs.gpredict
    pkgs.gqrx
    pkgs.graphinder
    pkgs.graphqlmap
    pkgs.graphw00f
    pkgs.grype
    pkgs.gsocket
    pkgs.hackrf
    pkgs.haka
    pkgs.hakrawler
    pkgs.hash_extender
    pkgs.hash-identifier
    pkgs.hashcat
    pkgs.hashcat-utils
    pkgs.hashdeep
    pkgs.hashpump
    pkgs.hashrat
    pkgs.hcxdumptool
    pkgs.hcxtools
    pkgs.hexbinhex
    pkgs.holehe
    pkgs.honggfuzz
    pkgs.hopper
    pkgs.hostapd-mana
    pkgs.hping
    pkgs.httping
    pkgs.httprobe
    pkgs.httptunnel
    pkgs.httpx
    pkgs.hyenae
    pkgs.i2pd
    pkgs.iaito
    pkgs.ike-scan
    pkgs.interactsh
    pkgs.iodine
    pkgs.ipmitool
    pkgs.iputils
    pkgs.jadx
    pkgs.jaeles
    pkgs.jd-gui
    pkgs.jnetmap
    pkgs.joomscan
    pkgs.jpexs
    pkgs.jsbeautifier
    pkgs.junkie
    pkgs.jwt-hack
    pkgs.kalibrate-rtl
    pkgs.katana
    pkgs.kerbrute
    pkgs.kismet
    pkgs.kiterunner
    pkgs.klee
    pkgs.kube-hunter
    pkgs.ldapdomaindump
    pkgs.ldeep
    pkgs.libargon2
    pkgs.libbde
    pkgs.libewf
    pkgs.libgcrypt
    pkgs.libosmocore
    pkgs.libpst
    pkgs.libtins
    pkgs.lief
    pkgs.ligolo-ng
    pkgs.linux-exploit-suggester
    pkgs.lldb
    pkgs.loadlibrary
    pkgs.log4j-scan
    pkgs.ltrace
    pkgs.lynis
    pkgs.macchanger
    pkgs.mailsend
    pkgs.maltego
    pkgs.mapcidr
    pkgs.masscan
    pkgs.mdbtools
    pkgs.mdk4
    pkgs.medusa
    pkgs.metabigor
    pkgs.metasploit
    pkgs.mfcuk
    pkgs.mfoc
    pkgs.miredo
    pkgs.mitm6
    pkgs.mitmproxy
    pkgs.mitmproxy2swagger
    pkgs.mongoaudit
    pkgs.monsoon
    pkgs.ms-sys
    pkgs.mubeng
    pkgs.multimon-ng
    pkgs.naabu
    pkgs.nasm
    pkgs.nbtscanner
    pkgs.ncrack
    pkgs.netdiscover
    pkgs.netmask
    pkgs.netsniff-ng
    pkgs.networkminer
    pkgs.nfdump
    pkgs.ngrep
    pkgs.ngrok
    pkgs.nikto
    pkgs.nosqli
    pkgs.ntlmrecon
    pkgs.nuclei
    pkgs.obfs4
    pkgs.octosuite
    pkgs.oletools
    pkgs.onesixtyone
    pkgs.osslsigncode
    pkgs.ostinato
    pkgs.p0f
    pkgs.packer
    pkgs.padbuster
    pkgs.parsero
    pkgs.pcapfix
    pkgs.pdf-parser
    pkgs.pdfcrack
    pkgs.pe-bear
    pkgs.pev
    pkgs.photon
    pkgs.phrasendrescher
    pkgs.pixd
    pkgs.pixiewps
    pkgs.plecost
    pkgs.pmacct
    pkgs.pngcheck
    pkgs.powersploit
    pkgs.procdump
    pkgs.procyon
    pkgs.proxify
    pkgs.proxmark3
    pkgs.proxychains-ng
    pkgs.psudohash
    pkgs.pwnat
    pkgs.pwncat
    pkgs.pwndbg
    pkgs.pwntools
    pkgs.python311Packages.angr
    pkgs.python311Packages.angrop
    pkgs.python311Packages.distorm3
    pkgs.python311Packages.impacket
    pkgs.python311Packages.patator
    pkgs.python311Packages.pwntools
    pkgs.python311Packages.ropgadget
    pkgs.python311Packages.ropper
    pkgs.python312Packages.arsenic
    pkgs.python312Packages.dnspython
    pkgs.python312Packages.frida-python
    pkgs.python312Packages.httpx
    pkgs.python312Packages.impacket
    pkgs.python312Packages.ldapdomaindump
    pkgs.python312Packages.minidump
    pkgs.python312Packages.minikerberos
    pkgs.python312Packages.myjwt
    pkgs.python312Packages.netmap
    pkgs.python312Packages.pcodedmp
    pkgs.python312Packages.pyaxmlparser
    pkgs.python312Packages.pyjsparser
    pkgs.python312Packages.pypykatz
    pkgs.python312Packages.rfcat
    pkgs.python312Packages.scapy
    pkgs.python312Packages.shodan
    pkgs.python312Packages.spyse-python
    pkgs.python312Packages.sshtunnel
    pkgs.python312Packages.thefuzz
    pkgs.python312Packages.torpy
    pkgs.python312Packages.vt-py
    pkgs.python312Packages.websockify
    pkgs.python312Packages.yara-python
    pkgs.quark-engine
    pkgs.radamsa
    pkgs.radare2
    pkgs.rarcrack
    pkgs.rathole
    pkgs.reaverwps-t6x
    pkgs.recoverjpeg
    pkgs.redfang
    pkgs.redsocks
    pkgs.regripper
    pkgs.responder
    pkgs.retdec
    pkgs.rinetd
    pkgs.rita
    pkgs.rizin
    pkgs.rizinPlugins.rz-ghidra
    pkgs.ropgadget
    pkgs.routersploit
    pkgs.rr
    pkgs.ruler
    pkgs.rustcat
    pkgs.rustscan
    pkgs.safecopy
    pkgs.saleae-logic
    pkgs.saleae-logic-2
    pkgs.samplicator
    pkgs.scanmem
    pkgs.seclists
    pkgs.sha1collisiondetection
    pkgs.shellnoob
    pkgs.sherlock
    pkgs.siege
    pkgs.sipvicious
    pkgs.sleuthkit
    pkgs.slither-analyzer
    pkgs.slowhttptest
    pkgs.slowlorust
    pkgs.smbmap
    pkgs.sn0int
    pkgs.snallygaster
    pkgs.sniffglue
    pkgs.snmpcheck
    pkgs.snort
    pkgs.snow
    pkgs.snowman
    pkgs.snscrape
    pkgs.snyk
    pkgs.soapui
    pkgs.socat
    pkgs.social-engineer-toolkit
    pkgs.socialscan
    pkgs.spiped
    pkgs.sqlmap
    pkgs.ssdeep
    pkgs.ssh-audit
    pkgs.ssh-mitm
    pkgs.sshocker
    pkgs.sshuttle
    pkgs.ssldump
    pkgs.sslh
    pkgs.sslscan
    pkgs.sslsplit
    pkgs.stacs
    pkgs.strace
    pkgs.stunnel
    pkgs.subfinder
    pkgs.subjs
    pkgs.suricata
    pkgs.swaks
    pkgs.sysdig
    pkgs.tcpdump
    pkgs.tcpflow
    pkgs.tcpreplay
    pkgs.tcpreplay
    pkgs.tcptraceroute
    pkgs.tell-me-your-secrets
    pkgs.testdisk
    pkgs.testssl
    pkgs.tfsec
    pkgs.thc-hydra
    pkgs.thc-ipv6
    pkgs.theharvester
    pkgs.tinc
    pkgs.tinyproxy
    pkgs.tlsx
    pkgs.tor
    pkgs.torsocks
    pkgs.traceroute
    pkgs.trivy
    pkgs.truecrack
    pkgs.trufflehog
    pkgs.tshark
    pkgs.udis86
    pkgs.udp2raw
    pkgs.udpreplay
    pkgs.udptunnel
    pkgs.uncover
    pkgs.upx
    pkgs.urh
    pkgs.usbrip
    pkgs.valgrind
    pkgs.veracrypt
    pkgs.vivisect
    pkgs.vgrep
    pkgs.volatility3
    pkgs.vt-cli
    pkgs.wafw00f
    pkgs.wapiti
    pkgs.wavemon
    pkgs.wcc
    pkgs.webanalyze
    pkgs.websploit
    pkgs.wfuzz
    pkgs.whatweb
    pkgs.whispers
    pkgs.wifite2
    pkgs.wireshark
    pkgs.wpscan
    pkgs.wuzz
    pkgs.wxhexeditor
    pkgs.xcat
    pkgs.xortool
    pkgs.xsser
    pkgs.yara
    pkgs.yersinia
    pkgs.zap
    pkgs.zdns
    pkgs.zeek
    pkgs.zgrab2
    pkgs.zmap
    pkgs.zssh
    pkgs.zulu
    pkgs.zzuf
    ];
}
